apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: bednarmaros341/napmap-ufe
    newName: bednarmaros341/napmap-ufe
    newTag: 1.1.0

  - name: bednarmaros341/napmap-webapi
    newName: bednarmaros341/napmap-webapi
    newTag: 1.0.3
