apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: mb-napmap-gitops
  namespace: wac-hospital
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: mb-gitops-repo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "Automated image update by Flux"
    push:
      branch: main
  update:
    path: ./components
    strategy: Setters
