apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
    - pairs:
          app.kubernetes.io/part-of: wac-hospital
namespace: wac-hospital
resources:
    - cd.kustomization.yaml
    - install.kustomization.yaml
    - git-repository.yaml
    - napmap-ufe.image-repository.yaml
    - napmap-ufe.image-policy.yaml
    - napmap-webapi.image-repository.yaml
    - napmap-webapi.image-policy.yaml
    - image-update-automation.yaml
    - project.yaml
