apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: mb-napmap-webapi-mongodb-init
    files:
      - init-db.js

labels:
  - pairs:
      app.kubernetes.io/component: mb-napmap-webapi
