apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wac-hospital
labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital
resources:
  - ../../../apps/mb-napmap-ufe
  - ../../../apps/mb-napmap-webapi

patches:
  - path: patches/napmap-webapi.service.yaml

components:
  - ../../../components/version-developers
  - https://github.com/Marosko123/napmap-webapi//deployments/kustomize/components/mongodb
